POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUyMzU1Nzc5LCJ1c2VySWQiOjJ9.9Y6VhJur1P_7ZbTl7i0ZdC6ZNSn8E5XusnMg4zgy6LE

{
  "name": "old test Event",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2025-07-05T14:53:00.000Z"
}