POST http://localhost:8080/events
content-type: application/json

{
  "name": "test Event",
  "description": "A test event",
  "location": "A test location",
  "dateTime": "2025-07-05T14:53:00.000Z"
}