GET http://localhost:8080/events
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUyMTczNDQ2LCJ1c2VySWQiOjJ9.ApI_osHCtP7fQGR0i1mMcNiXrhmpfYPdhAb4RGty2AQ
