POST http://localhost:8080/events/12/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzUyMzU1Nzc5LCJ1c2VySWQiOjJ9.9Y6VhJur1P_7ZbTl7i0ZdC6ZNSn8E5XusnMg4zgy6LE